
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculDistanceService", targetNamespace = "http://SOAP/", wsdlLocation = "https://soap-calculdistance.herokuapp.com/services/CalculDistance?wsdl")
public class CalculDistanceService
    extends Service
{

    private final static URL CALCULDISTANCESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULDISTANCESERVICE_EXCEPTION;
    private final static QName CALCULDISTANCESERVICE_QNAME = new QName("http://SOAP/", "CalculDistanceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://soap-calculdistance.herokuapp.com/services/CalculDistance?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULDISTANCESERVICE_WSDL_LOCATION = url;
        CALCULDISTANCESERVICE_EXCEPTION = e;
    }

    public CalculDistanceService() {
        super(__getWsdlLocation(), CALCULDISTANCESERVICE_QNAME);
    }

    public CalculDistanceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULDISTANCESERVICE_QNAME, features);
    }

    public CalculDistanceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULDISTANCESERVICE_QNAME);
    }

    public CalculDistanceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULDISTANCESERVICE_QNAME, features);
    }

    public CalculDistanceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculDistanceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculDistance
     */
    @WebEndpoint(name = "CalculDistancePort")
    public CalculDistance getCalculDistancePort() {
        return super.getPort(new QName("http://SOAP/", "CalculDistancePort"), CalculDistance.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculDistance
     */
    @WebEndpoint(name = "CalculDistancePort")
    public CalculDistance getCalculDistancePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAP/", "CalculDistancePort"), CalculDistance.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULDISTANCESERVICE_EXCEPTION!= null) {
            throw CALCULDISTANCESERVICE_EXCEPTION;
        }
        return CALCULDISTANCESERVICE_WSDL_LOCATION;
    }

}
